### ISSUE TITLE
seafile-pro_uberspace

### ISSUE THREAD

**Issue by tristan-k** [SeafileDE/seafile-server-installer#48]
There is [free](https://shop.seafile.de/produkt/seafile-professional-kostenlos/) professional version available for seafile which is limited to three users. I would appreciate a  setup script for the professional version for uberspace.

**Comment by alexanderjackson** [comment]
Thanks for pointing that out. However, we are quite aware that we offer the free Seafile Professional version there ;-).

Unfortunately, Seafile Professional cannot be installed on an Uberspace. At least not without heavy customization (virtual environment) within the confined Uberspace itself. If you find an easy way to get indexing and the office preview done, I am willing to reconsider this decision.

**Comment by shoeper** [comment]
> indexing

Requires java, don't think it'll work on uberspace because it needs tons of ram.

**Comment by alexanderjackson** [comment]
However, you can't really save a lot of data within a Uberspace itself anyway. I think it's approx. 10GB. So RAM usage might not be that high after all. Not sure though...

**Comment by shoeper** [comment]
Afaik elastic search starts up using a few hundret MiB of RAM. 
Regarding java von uberspace see also https://wiki.uberspace.de/brainstorming#java (german)

**Comment by alexanderjackson** [comment]
Looks like Java and maybe LibreOffice could be run within the confined (Uber)space. However available RAM simple seems to be the biggest issue. Not sure how much RAM a Uberspace is allowed to use or occupy permanently. Personally I think the setup would be to messy. If it technically works, it's probably only worth as proof of concept since Uberspace most-likely will forbid this setup on their servers it in the long run. They might even consider banning users. So it's probably not worth the hassle...

**Comment by tristan-k** [comment]
Actually the reason for choosing the free professional version was the possiblity to have selective folder sync available. Is there a way to opt-out of all the java related stuff.

**Comment by shoeper** [comment]
You can try to install it without indexing and office preview.

**Comment by alexanderjackson** [comment]
If I am not mistaking, that should work...
